name: XKickUI
version: 1.0.0
api: 3.0.0
main: JukaChance\XKickUI\XKickUI
authors:
  - JukaChance
  - supercrafter333

permissions:
  XKickUI.xkickui.cmd:
    description: Command permission
    default: op